### ISSUE TITLE
Font For The Hacking List

### ISSUE THREAD

**Issue by WNGDarkleader** [Wurst-Imperium/Wurst-Client-Bugs#65] opened 2016-06-03 12:37 UTC
The Font In GUI Is Messed Up
It looks like if it was typed in Chinese and it is impossible to read  I expected to it be in American. It was unreadable.

#### How to Reproduce the Bug
Download it then put it in the versions folder, then login. I don't know to get it.

#### Other Information
- Wurst Client version: 3.3
- Operating system: Windows 7

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by mcccs** [comment] 2016-06-03 13:53
Delete everything (except `saves` and `servers.dat` and `options.txt`) in `.minecraft`
Then install Wurst again.

**Comment by Alexander01998** [comment] 2016-06-04 06:23
Appears tp be a duplicate of #59.

**Closed by Alexander01998** 2016-06-04 06:23 UTC

**Comment by WNGDarkleader** [comment] 2016-06-06 17:54
Thank you very much.

Have A Good Day
